[package]
name = "imdb-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.40.0", features = ["full"] }
