[package]
name = "imdbsql"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.40.0", features = ["full"] }
